version: "3.8"

services:
  web:
    image: brickstreammainweb:latest
    container_name: brickstream_main_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
