version: "3.8"

services:
  web:
    image: storynation-frontend-live-v0.3.8
    container_name: storynation-frontend
    ports:
      - "3201:3000"
    environment:
      - NODE_ENV=production
    restart: always
